version: '3'

services:

  gateway: 
    container_name: gateway
    image: brulejr/gateway
    ports:
      - "8060:8060"
    depends_on:
      - keycloak

  keycloak-db:
    container_name: keycloak-db
    image: postgres:13-alpine
    volumes: 
      - keycloak-datastore:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB:       keycloak
      POSTGRES_USER:     keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    depends_on:
      - keycloak-db
    ports:
      - "8888:8080"
    environment:
      DB_VENDOR:   POSTGRES
      DB_ADDR:     keycloak-db
      DB_PORT:     5432
      DB_DATABASE: keycloak
      DB_USER:     keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER:     spring
      KEYCLOAK_PASSWORD: spring123

volumes:
  keycloak-datastore:
