version: '3.9'

services:

  ping:
    image: brulejr/ping
    networks:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_BASEURL: http://keycloak:8080
  
  gateway:
    image: brulejr/gateway
    networks:
      - backend
    ports:
      - "8060:8060"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KEYCLOAK_BASEURL: http://localhost:8888
      KEYCLOAK_BASEURL_INTERNAL: http://keycloak:8080
      KEYCLOAK_CLIENT_ID_FILE: /run/secrets/keycloak_client_id
      KEYCLOAK_CLIENT_SECRET_FILE: /run/secrets/keycloak_client_secret
      PING_BASEURL: http://ping:8040
    secrets:
      - keycloak_client_id
      - keycloak_client_secret

  keycloak-db:
    image: postgres:13-alpine
    networks:
      - backend
    volumes: 
      - keycloak-datastore:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  keycloak:
    image: jboss/keycloak
    networks:
      - backend
    depends_on:
      - keycloak-db
    ports:
      - "8888:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD_FILE: /run/secrets/db_password
      KEYCLOAK_USER_FILE: /run/secrets/keycloak_user
      KEYCLOAK_PASSWORD_FILE: /run/secrets/keycloak_password
    secrets:
      - db_password
      - keycloak_user
      - keycloak_password
    
secrets:
  db_password:
    external: yes
  keycloak_client_id:
    external: yes
  keycloak_client_secret:
    external: yes
  keycloak_password:
    external: yes
  keycloak_user:
    external: yes
    

volumes:
  keycloak-datastore:

networks:
  backend:
