version: '3.9'

services:

  keycloak-db:
    container_name: keycloak-db
    image: postgres:13-alpine
    networks:
      - backend
    volumes: 
      - keycloak-datastore:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password

  keycloak:
    container_name: keycloak
    image: jboss/keycloak
    networks:
      - backend
    depends_on:
      - keycloak-db
    ports:
      - "8888:8080"
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD_FILE: /run/secrets/db_password
      KEYCLOAK_USER_FILE: /run/secrets/keycloak_user
      KEYCLOAK_PASSWORD_FILE: /run/secrets/keycloak_password
    secrets:
      - db_password
      - keycloak_user
      - keycloak_password
    
secrets:
  db_password:
    external: yes
  keycloak_user:
    external: yes
  keycloak_password:
    external: yes

volumes:
  keycloak-datastore:

networks:
  backend:
