pipeline {
    agent {
        docker {
            image 'gradle:7-jdk11'
            reuseNode true
        }
    }
    environment {
        DOCKER_IMAGE = "gateway"
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        SSH = "#ssh -o StrictHostKeyChecking=no -l ${DOCKER_DEPLOY_USER} ${DOCKER_DEPLOY_HOST}"
    }
    stages {
        stage ('Checkout') {
            steps {
                checkout scm
                sh 'ls -lat'
            }
        }
        stage("Build") {
            steps {
                sh 'gradle gateway:clean gateway:build'
                junit "**/build/test-results/test/*.xml"
                jacoco(
                    execPattern: 'build/jacoco/jacoco.exec'
                )
            }
        }
        stage('Publish') {
            steps {
                sh "gradle gateway:jib"
            }
        }
    }
}
